# Generated by Django 4.2.11 on 2024-05-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance_sys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbr", models.CharField(max_length=10)),
                ("branch", models.CharField(max_length=200)),
            ],
        ),
    ]
