# Generated by Django 4.2.11 on 2024-05-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance_sys", "0002_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="branch",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="course",
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="roll_num",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(default="Absent", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="year",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="branch",
            field=models.CharField(
                choices=[
                    ("CSE", "CSE"),
                    ("AIDE", "AIDE"),
                    ("BSBE", "BSBE"),
                    ("Chemical Engg", "Chemical Engg"),
                    ("Chemistry", "Chemistry"),
                    ("Physics", "Physics"),
                    ("CI", "CI"),
                    ("MECH", "MECH"),
                    ("EE", "EE"),
                    ("MT", "MT"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_num",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="year",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                max_length=10,
                null=True,
            ),
        ),
    ]
