# Generated by Django 4.2.11 on 2024-05-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "attendance_sys",
            "0003_alter_attendance_branch_alter_attendance_course_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="end_time",
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="start_time",
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
