# Generated by Django 4.2.11 on 2024-05-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance_sys", "0004_alter_attendance_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="start_time",
            field=models.TimeField(null=True),
        ),
    ]
